# Generated by Django 5.0.7 on 2024-09-30 10:51

import myauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=myauth.models.profile_avatars_directory_path
            ),
        ),
    ]
