version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always
    # environment:
      # DJANGO_LOGLEVEL: WARNING  # минусы: если захотим указать другие правила логирования, то придется менять докер-компос файл -> изменения в гитерепозитории -> возможны конфликты
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    
    volumes:
      - ./mysite/database:/app/database
