# Generated by Django 5.0.7 on 2024-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(default="lala"),
        ),
    ]
