# Generated by Django 5.0.7 on 2024-09-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_product_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(null=True, upload_to="ordres/receipts/"),
        ),
    ]
