# Generated by Django 5.0.7 on 2024-10-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0006_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "order", "verbose_name_plural": "orders"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
